### ISSUE TITLE
BinaryTree and BinarySearchTree

### ISSUE THREAD

**Issue by nicosammito** [Th3Ph4nt0m/Info_2020#5]
Hey,

is it possible to add the BinaryTree and the BinarySearchTree to the "ABI" folder, because those classes are included in the NRW Abi.

Best regards
Nico

**Comment by Th3Ph4nt0m** [comment]
Hey Nico,

you can find all implementations and documentations for the Abitur in NRW [here](https://www.schulentwicklung.nrw.de/lehrplaene/lehrplannavigator-s-ii/gymnasiale-oberstufe/informatik/hinweise-und-beispiele/hinweise-und-beispiele.html#a2). As this repository is only a space for the work I do in school, I will add the classes as soon as I need them.

I hope this link helps you well!
